version: '3'

services:
  news-db:
    image: postgres
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
    volumes:
      - /var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - news-database
    ports:
      - 5432:5432

  news-mongo:
    image: bitnami/mongodb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /bitnami/mongodb
    networks:
      - news-database
    ports:
      - 27017:27017

  news-service:
    image: news-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8084:8084
    volumes:
      - /data/news-service
    networks:
      - news-database
      - network

networks:
  news-database:
    driver: bridge
  network:
    driver: bridge
