version: '3'

services:
  news-mongo:
    image: bitnami/mongodb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - /bitnami/mongodb
    networks:
      - news-database
    ports:
      - 27017:27017

  news-service:
    image: news-service
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8084:8084
    volumes:
      - /data/news-service
    networks:
      - news-database
      - network

networks:
  news-database:
    driver: bridge
  network:
    driver: bridge
