openapi: 3.0.3
info:
  title: API Specification for News-Service
  description: API Specification for News-Service
  version: 1.0.0
servers:
  - url: 'http://localhost:8084/api/news'
paths:
  /:
    get:
      description: Find News for the authenticated user.
      responses:
        '200':
          description: News
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfNews'
        '404':
          description: User not found
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: string
  /admin/all:
    get:
      description: Returns all News saved. ADMIN only.
      responses:
        '200':
          description: List of News
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfNews'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                type: string

components:
  schemas:
    News:
      type: object
      properties:
        eventCode:
          type: string
        eventData:
          type: object
        issueId:
          type: string
          nullable: true
        projectId:
          type: string
          nullable: true
        userId:
          type: string
          nullable: true
        newsId:
          type: string
        timestamp:
          type: string
          nullable: true

    ArrayOfNews:
      type: array
      items:
        $ref: '#/components/schemas/News'
